Tobias - responzivita vyukovy mod
Nunanda/Selecro-webovky pull request #7
Opened 2022-10-19 19:59 UTC by t0b1aas

Pozmenil jsem par veci, kvuli responzivite ve vyukovem modu

2022-10-21 06:38 UTC, vendybike requested changes

2022-10-21 06:38 UTC, vendybike commented on src/app/pages/vyukovymod/vyukovymod.component.css
>  #obrázek_návodu {
Nepouzivat interpunkci prosim

2022-10-21 06:38 UTC, vendybike commented on src/app/pages/vyukovymod/vyukovymod.component.html
> -                    <title class="Název_návodu">
Interpunkce.

2022-10-21 06:38 UTC, vendybike commented on src/app/pages/vyukovymod/vyukovymod.component.html
> -                    <img id="obrázek_návodu" src="../assets/icon/{{vyrobek.nazev}}.jpg">
taky interpunkce

2022-10-21 06:38 UTC, vendybike commented on src/app/pages/vyukovymod/vyukovymod.component.html
> +                    <img id="obrázek_návodu" src="../assets/icon/Chobotnicka.jpg">
Interpunkce

2022-10-21 06:38 UTC, vendybike commented on src/app/pages/vyukovymod/vyukovymod.component.html
> -                    <img id="obrázek_návodu" src="../assets/icon/{{vyrobek.nazev}}.jpg">
taky

2022-10-21 06:38 UTC, vendybike commented on src/app/pages/vyukovymod/vyukovymod.component.html
>                      <img id="obrázek_návodu" src="../assets/icon/Chobotnicka.jpg">
taky interpunkce

2022-10-21 09:19 UTC, Szotkowski reviewed
Dobré

2022-10-21 09:20 UTC, Szotkowski approved these changes
Dobré

2022-10-23 17:54 UTC, vendybike approved these changes

2022-10-23 17:54 UTC, merged